---
title           : "Study preregistration"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Megan Duchesne



output: prereg::prereg_pdf
bibliography: references.bib
---

# Study Information

## Title

Does novel competition drive selection on morphology?

````{=html}
<!-- Provide the working title of your study. It may be the same title that you submit for publication of your final manuscript, but it is not a requirement. The title should be a specific and informative description of a project. Vague titles such as 'Fruit fly preregistration plan' are not appropriate.

```
## Description

```{=html}
<!-- Please give a brief description of your study, including some background, the purpose of the of the study, or broad research questions. The description should be no longer than the length of an abstract. It can give some context for the proposed study, but great detail is not needed here for your preregistration.

Example: Though there is strong evidence to suggest that sugar affects taste preferences, the effect has never been demonstrated in brownies. Therefore, we will measure taste preference for four different levels of sugar concentration in a standard brownie recipe to determine if the effect exists in this pastry. -->
````

Through their long-term, empirical study @grant2006 provided one of the few examples of natural selection acting on traits in a native population in response to novel competition and despite their call for future studies to replicate their work, none have done so. Therefore, we will use 49 years of data to replicate @grant2006 by testing for selection on bills in a native population of birds in response to novel competition for seeds with a non-native population of birds.

## Hypotheses

```{=html}
<!-- List specific, concise, and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here. If a specific interaction or moderation is important to your research, you can list that as a separate hypothesis.

Example: If taste affects preference, then mean preference indices will be higher with higher concentrations of sugar. -->
```
We are investigating whether bill size influences survival in song sparrows.

### Predictions

Given that fox sparrows are the larger, dominant competitor and reduce over-winter survival in song sparrows, we expect directional selection to be acting on the bills of song sparrows throughout the study, and have alternative predictions regarding the outcome of selection on bills depending on whether niche differentiation from fox sparrows is possible on such a small island (6ha):

a\. Given selection in favor of niche differentiation from fox sparrows (broad feeding niche), we expect directional selection to cause a reduction in bill size (PC1) of song sparrows over time, as predicted by @grant2006.

b\. Alternatively, given selection in favor of maximizing feeding efficiency on the limited and relatively large seeds on Mandarte Island (narrow feeding niche), we instead expect directional selection to cause an increase in bill size (PC1) of song sparrows over time, as predicted by @abrams1987 and @johnson2018.

# Design Plan

<!-- In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. -->

## Study type

**Observational Study**. Data is collected from study subjects that are not randomly assigned to a treatment. This includes surveys, natural experiments, and regression discontinuity designs.

## Blinding

<!-- Blinding describes who is aware of the experimental manipulations within a study. Select all that apply. Is there any additional blinding in this study? -->

No blinding is involved in this study.

## Study design

```{=html}
<!-- Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies.

This question has a variety of possible answers. The key is for a researcher to be as detailed as is necessary given the specifics of their design. Be careful to determine if every parameter has been specified in the description of the study design. There may be some overlap between this question and the following questions. That is OK, as long as sufficient detail is given in one of the areas to provide all of the requested information. For example, if the study design describes a complete factorial, 2 X 3 design and the treatments and levels are specified previously, you do not have to repeat that information.

Example: We have a between subjects design with 1 factor (sugar by mass) with 4 levels. -->
```
This empirical study was started by Jamie Smith in 1975, so while this pre-registration does not precede data collection, the methods for monitoring and collecting data on the song sparrows of Manadarte Island were used consistently for the past 49 years and are described in detail in [@conserva2006]. In short, all birds are uniquely identified by their combination of colored bands and a numbered metal band (hereby bind identity), allowing researchers to track individuals from hatching until their disappearance. Because birds are banded as nestlings, we know their exact age at any given time, they are captured in mist nets and measured throughout their lives, and once they become territorially active we identify their sex.

# Sampling Plan

<!-- In this section we’ll ask you to describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Please keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study. -->

## Existing data

<!-- Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data. Therefore, creating a research plan in which existing data will be used presents unique challenges. Please select the description that best describes your situation. Please do not hesitate to contact us if you have questions about how to answer this question (prereg@cos.io). -->

**Registration following analysis of the data**. As of the date of submission, you have accessed and analyzed some of the data relevant to the research plan. This includes preliminary analysis of variables, calculation of descriptive statistics, and observation of data distributions. Please see <https://cos.io/prereg> for more information.

## Explanation of existing data

```{=html}
<!-- If you indicate that you will be using some data that already exist in this study, please describe the steps you have taken to assure that you are unaware of any patterns or summary statistics in the data. This may include an explanation of how access to the data has been limited, who has observed the data, or how you have avoided observing any analysis of the specific data you will use in your study.

An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point.

Example: An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point. -->
```
As inidicated above, I am creating this pre registration after having analyzed my data. But I planned my hypothesis, predictions, and analyses prior to analyzing my data while submitting an application for funding (NSERC-CGSM, which I imagine is available online). I finished collecting my data in August 2023 which was well after the application for funding was due (December 2022), so thats as much of a guarantee as I can give that I did not review my data before planning my study.

## Data collection procedures

```{=html}
<!-- Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that donÍt include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.

The answer to this question requires a specific set of instructions so that another person could repeat the data collection procedures and recreate the study population. Alternatively, if the study population would be unable to be reproduced because it relies on a specific set of circumstances unlikely to be recreated (e.g., a community of people from a specific time and location), the criteria and methods for creating the group and the rationale for this unique set of subjects should be clear.

Example: Participants will be recruited through advertisements at local pastry shops. Participants will be paid $10 for agreeing to participate (raised to $30 if our sample size is not reached within 15 days of beginning recruitment). Participants must be at least 18 years old and be able to eat the ingredients of the pastries. -->
```
## Repeatable procedures:

Our study is working to replicate @grant2006 which focused on two populations of finches in the Galapagos Islands. Clearly our focus species and location is different but the principles are the same:

**Monitoring birds**

Birds are uniquely identified and monitored consistently throughout the breeding season (at least weekly from April-August) throughout the entire study.

**Morphology measures**

Birds are captured in mist-nets and measurements of bill length, depth and width are taken using vernier calipers to the nearest 0.1mm. A consistent effort to capture and measure birds was employed throughout the study. To ensure high repeatability of measures among observers, the same observer measured birds and trained other observers to measure similarly for 41 of 49 years. Only fully-grown birds will be used in analyses. @smith1979 found song sparrows were fully grown at 58 days old.

**Survival status**

Over-winter survival is used to measure selection on song sparrows, following @johnson2018, which is assessed in April each year and is scored as a binary response. Birds are considered to have survived if they were seen with two independent sighting or a very confident sighting (ie. caught in a net, there were notes that bands were double-checked, or bird movement mapped by a skilled observer).

## Location/species-specific circumstances potentially affecting repeatability:

There are several distinct features about the species and location used in our study that would need to be considered carefully by a future researcher attempting to replicate:

1.  Mandarte Island is the only recorded place where song and fox sparrows compete for food. Unlike mainland populations, native populations on oceanic islands can be subject to greater competition with invasive species for food resources [@soares2021]. The island is made up of bare rock and a handful of shrub species that produce seeds for the sparrows to feed on, however, they overlap completely for their preference of seeds [@johnson2018]. The geographical location and vegetation of Mandarte likely make the competitive environment here unique and its hard to say whether these species would compete under different conditions.
2.  Song sparrows are widespread and vary dramatically in morphology across their range, and even vary within the Haro Straight metapopulation that the song sparrows of Mandarte Island exist in. This study is driven by the contrast in size between song and fox sparrows, but if this study was repeated somewhere in the world where the size difference between song and fox sparrows is different than this study, it would be hard to say whether the researchers would find the same results.
3.  Historically, fox sparrows were considered to be a migratory species, but populations in the Haro Straight have contradicted this since the late 1970s when individuals began over-wintering on islands in the straight, including Mandarte. Because this is an empirical study, a future study would need to also rely on having data available before a novel competitor (fox sparrows) colonized the island (1975 in this case) as well as in the several decades following this colonization.

## Sample size

```{=html}
<!-- Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis? For some studies, this will simply be the number of samples or the number of clusters. For others, this could be an expected range, minimum, or maximum number.

Example: Our target sample size is 280 participants. We will attempt to recruit up to 320, assuming that not all will complete the total task. -->
```
Because of the monitoring effort on Mandarte Island, this study does not focus on a sample but rather the entire population. The population varies dramatically in size over time, but years with low population sizes are still useful because they help inform how/why selection may be acting. That being said, the planned analyses include combining all years into one model so small population sizes in certain years are not of concern for running models.

## Sample size rationale

```{=html}
<!-- This could include a power analysis or an arbitrary constraint such as time, money, or personnel. This gives you an opportunity to specifically state how the sample size will be determined. A wide range of possible answers is acceptable; remember that transparency is more important than principled justifications. If you state any reason for a sample size upfront, it is better than stating no reason and leaving the reader to "fill in the blanks." Acceptable rationales include: a power analysis, an arbitrary number of subjects, or a number based on time or monetary constraints.

Example: We used the software program G*Power to conduct a power analysis. Our goal was to obtain .95 power to detect a medium effect size of .25 at the standard .05 alpha error probability. -->
```
Not applicable.

## Stopping rule

```{=html}
<!-- If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. 

You may specify a stopping rule based on p-values only in the specific case of sequential analyses with pre-specified checkpoints, alphas levels, and stopping rules. Unacceptable rationales include stopping based on p-values if checkpoints and stopping rules are not specified. If you have control over your sample size, then including a stopping rule is not necessary, though it must be clear in this question or a previous question how an exact sample size is attained.

Example: We will post participant sign-up slots by week on the preceding Friday night, with 20 spots posted per week. We will post 20 new slots each week if, on that Friday night, we are below 320 participants. -->
```
In 2023 the song sparrow population became functionally extirpated given that no females on the island were resident birds. The only females were immigrant birds from nearby islands who genetically differ a surprising amount from resident birds. The immigrant genes are causing the population to be quite unlike the resident population at the beginning of the study (e.g. fitness). Further justification is that our work provides us with 49 years of selection data which is more than the 33 years of the study we are emulating [@grant2006]. Finally, the principle investigator and project supervisor are retiring.

# Variables

<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->

## Measured variables

```{=html}
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.'

Example: The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being 'not at all', 7 being 'a great deal') and 'How good did the brownie taste' (on a scale of 1-7, 1 being 'very bad', 7 being 'very good'). -->
```
-   Survival is measured as a binary response.

-   Using bird identity we will calculate an average bill length, depth and width for each for each bird, taking advantage of repeat measures of individuals to maximize precision and correct for variation among observers. Bill length, depth and width will then be reduced to two morphological characters by extracting the first two principal components: PC1 bill size and PC2 bill shape.

# Analysis Plan

```{=html}
<!-- You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.

A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. -->
```
I will calculate selection gradients to test for directional selection on traits.

**Dependent=** Survival (0,1)

**Independent**=Bill size (PC1), Bill shape (PC2)

## Statistical models

```{=html}
<!-- What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions, subgroup analyses, pairwise or complex contrasts, or follow-up tests from omnibus tests. If you plan on using any positive controls, negative controls, or manipulation checks you may mention that here. Remember that any test not included here must be noted as an exploratory test in your final article.

This is perhaps the most important and most complicated question within the preregistration. As with all of the other questions, the key is to provide a specific recipe for analyzing the collected data. Ask yourself: is enough detail provided to run the same analysis again with the information provided by the user? Be aware for instances where the statistical models appear specific, but actually leave openings for the precise test. See the following examples:

- If someone specifies a 2x3 ANOVA with both factors within subjects, there is still flexibility with the various types of ANOVAs that could be run. Either a repeated measures ANOVA (RMANOVA) or a multivariate ANOVA (MANOVA) could be used for that design, which are two different tests. 
- If you are going to perform a sequential analysis and check after 50, 100, and 150 samples, you must also specify the p-values you’ll test against at those three points.

Example:  We will use a one-way between subjects ANOVA to analyze our results. The manipulated, categorical independent variable is 'sugar' whereas the dependent variable is our taste index. -->
```
***Necessary context***: We will merge our file of averaged traits (1 row for each unique bird) with a survival file that contains one row for each year of a birds life (1+ rows for each unique bird) so that each bird is present in the data in each year it is alive and has an associated score (0,1) indicating whether it survives the following winter, but its traits are averaged across its life for maximum precision.

***Model*****:** We will separate our data to get 4 classes: fully grown female yearlings, fully grown male yearlings, adult females, adult males. We will test for selection within each class using generalized linear mixed models (GLMMs) using the glmer function from the lme4 package in R studio. The model will include the dependent and independent effects described above as well as 2 random effects. Year will be a random effect in each GLMM, while bird identity will be random effect only in GLMMs for adults because unique adults may appear in the data in multiple years while unique yearlings are only present in the data once.

## Transformations

```{=html}
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. If any categorical predictors are included in a regression, indicate how those variables will be coded (e.g. dummy coding, summation coding, etc.) and what the reference category will be.

Example: The "Effect of sugar on brownie tastiness" does not require any additional transformations. However, if it were using a regression analysis and each level of sweet had been categorically described (e.g. not sweet, somewhat sweet, sweet, and very sweet), 'sweet' could be dummy coded with 'not sweet' as the reference category. -->
```
We will follow other selection studies using morphological data which recommend z-standardizing traits prior to analyses [e.g., @grant2014; @mumme2023]. We found mixed opinions on whether traits should be ln-transformed prior to standardization [e.g., @schluter1986] so we will compare results when traits are and are not ln-transformed.

## Inference criteria

```{=html}
<!-- What criteria will you use to make inferences? Please describe the information youÍll use (e.g. p-values, bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this?

p-values, confidence intervals, and effect sizes are standard means for making an inference, and any level is acceptable, though some criteria must be specified in this or previous fields. Bayesian analyses should specify a Bayes factor or a credible interval. If you are selecting models, then how will you determine the relative quality of each? In regards to multiple comparisons, this is a question with few "wrong" answers. In other words, transparency is more important than any specific method of controlling the false discovery rate or false error rate. One may state an intention to report all tests conducted or one may conduct a specific correction procedure; either strategy is acceptable.

Example: We will use the standard p<.05 criteria for determining if the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct. The post-hoc Tukey-Kramer test adjusts for multiple comparisons. -->
```
We will use the standard p\<0.05 to test whether logistic regression suggest results are significantly different from those expected if the null hypothesis (no selection) were correct. The sign of the regression coefficients will indicate the direction of selection, which will inform our a-priori predictions. If models are unable to converge we may have to adjust the optimizer or number of iterations. If any bill size and shape are highly correlated we may have to remove one of them or analyze them separately, though we don't anticipate this to be an issue because using PCAs usually avoids this issue. If we find directional selection is not operating on traits we will test for stabilizing selection which is not what we expect to see but would only be operating if bills of song sparrows are near their phenotypic optimum.

## Data exclusion

```{=html}
<!-- How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? Will you use any awareness check? Any rule for excluding a particular set of data is acceptable. One may describe rules for excluding a participant or for identifying outlier data.

Example: No checks will be performed to determine eligibility for inclusion besides verification that each subject answered each of the three tastiness indices. Outliers will be included in the analysis. -->
```
We will only use birds which are fully grown (58 days or older). Male song sparrows are larger than females so when we clean the data we will separate the birds by sex then remove any measures which exceed 3 standard deviations from the trait mean. After this, measures for each unique bird will be averaged to increase precision and correct for variation among observers.

## Missing data

```{=html}
<!-- How will you deal with incomplete or missing data? Any relevant explanation is acceptable. As a final reminder, remember that the final analysis must follow the specified plan, and deviations must be either strongly justified or included as a separate, exploratory analysis.

Example: If a subject does not complete any of the three indices of tastiness, that subject will not be included in the analysis. -->
```
If an individual is missing a bill length, depth, or width measurement we will not be able to calculate PC1 or PC2 for the individual so they will not be included in analyses. If an individual does not have a survival status assigned (0,1) it will be omitted completely.

## Exploratory analyses (optional)

```{=html}
<!-- If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time.

Example: We expect that certain demographic traits may be related to taste preferences. Therefore, we will look for relationships between demographic variables (age, gender, income, and marital status) and the primary outcome measures of taste preferences. -->
```
Given that we have measures for wing, tarsus and mass as well we could calculate PC1 body size. We expect there could be some correlation between bill and body size but have no specific expectations as to whether selection is acting on body size.

# References

## 

```{=tex}
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
```
\noindent
